### ISSUE TITLE
Error regarding <?

### ISSUE THREAD

**Issue by hultberg** [Gert-dev/php-integrator-linter#11]
Hello

When using the linter in several projects I end up being focused on fixing errors because php-integrator (base or linter?) are not able to process the following valid php code:
````
<?php
$myVar = 'hey';

if ('hey' === $myVar) {
  ?>
  <strong><?=$myVar;?></strong>
<? } ?>    <-- Error here
````

Error message: `Syntax error, unexpected EOF`

**Comment by Gert-dev** [comment]
Hello. It seems that this is governed by the setting you have in your `php.ini`. If you have `short_open_tag = Off` (the default), this will produce an error and you can fix it by using `<?php` instead of `<?`. If you set `short_open_tag = On`, your code seems to index correctly here.

I must admit I've not explicitly tested PHP files containing partial output, so I was a bit surprised to see that it does (at least partially) work.

**Comment by hultberg** [comment]
@Gert-dev: Indeed. After setting `short_open_tag = On` I correcly linted the code.

**Comment by Gert-dev** [comment]
Good to hear! If you have any other problems, feel free to make tickets.
