### ISSUE TITLE
Variadic functions not

### ISSUE THREAD

**Issue by tillkruss** [Gert-dev/php-integrator-linter#18]
I'm getting warnings for all variadic functions. How can I prevent that?

The PHP versions is `PHP 5.6.13 (cli)`.

**Comment by Gert-dev** [comment]
Could you let me know what kind of warnings you are referring to? The linter is currently only indicating parsing errors from the main package, so any message that pops up should be a syntax error.

**Comment by tillkruss** [comment]
This is the error.

![screen shot 2016-03-13 at 10 22 59 am](https://cloud.githubusercontent.com/assets/665029/13730183/a2543c60-e905-11e5-958c-d469efd9989e.png)

**Comment by Gert-dev** [comment]
Do you happen to have two PHP versions installed and is a non-absolute path configured in the settings? If an incorrect older PHP version is being used by accident, that might explain why it's generating problems.

**Comment by tillkruss** [comment]
It's a standard OS X 10.11.3 installation

```
$ which php
/usr/local/opt/php56/bin/php
$ whereis php
/usr/bin/php
$ php --version
PHP 5.6.13 (cli) (built: Sep 21 2015 19:26:57)
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

I haven't touched the Atom settings either.

**Comment by Gert-dev** [comment]
Ok, IIRC the default in the settings panel is just `php`. I don't recognize `/usr/local/opt/php56/bin` as a default path in the system's PATH variable, is it possible that you are manually appending this path to your PATH variable (e.g. in your `.bashrc`)? I have had reports of issues (and experienced it myself) regarding Atom not inheriting any changes you make to your PATH variable, which would cause `/usr/bin/php` to be used anyway instead of `/usr/local/opt/php56/bin/php`.

Of course, if `/usr/bin/php` is also PHP >= 5.6, that can't be the problem. The only way to know for certain is to open the base package's settings and enter `/usr/local/opt/php56/bin/php` in the PHP path to see if that makes any difference.

Let me know if that helps.

**Comment by tillkruss** [comment]
Ah. I've added `/usr/local/opt/php56/bin` to the settings in Atom and now it's working. Sorry about that.

The version of `/usr/bin/php` is `PHP 5.5.30`.

**Comment by Gert-dev** [comment]
No problem, it certainly is confusing.
