### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by hultberg** [Gert-dev/php-integrator-linter#20]
When editing a file extending a class I get an error: `Class was not found`. The library that I use, where all sources are added as a project folder. This has been seen as a missing feature in integrator base. What makes this troubleling is that when I get a linter error because of this missing feature I don't see the point on why it is an developer error. Could this either be:
1. Disable the reporting until this mentioned feature is added
2. Adding support for multi folder projects

Thanks for your work on these packages. I would love to contribute if needed.

**Comment by hultberg** [comment]
This: `boolean was not found`

**Comment by Gert-dev** [comment]
If I understood correctly, you are getting the "class not found" error because the base package is not picking up multiple project folders?

The message regarding `boolean` is correct, I've decided against adding `boolean` as an alias for `bool` as the former is not mentioned in the upcoming PSR-5 yet [1], which would mean it is more future-proof to use `bool` instead.

Being able to disable the error messages is on the roadmap in any case, see also #19.

[1] https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#keyword

**Comment by hultberg** [comment]
@Gert-dev: Yes, that is correct. I suspect the base package is not picking up the other project folders in my project as I do not get autocomplete on them and they are not found. Is it required to have a `require` or `include` statement for classes? Because, the library uses a custom autoloading handler that resolves this in runtime.

Regarding `bool`, that fine. :+1:

**Comment by Gert-dev** [comment]
`require` or `include` should not be necessary. The indexer doesn't actually execute your code, but only looks at the namespace and the class name to determine what the full name is. As such, it should be independent of your autoloading (this used to be different but in version 0.4.0 of the base package this changed).

Regarding multiple root folders: that is indeed not supported yet at the moment. What you can do for now is put both folders inside a common folder and then use that common folder as your project folder. I'm tracking progress on this in a ticket in the base package [1]. I'll close this to keep the discussion and progress centralized there, but if you have more questions, feel free to ask.

[1] https://github.com/Gert-dev/php-integrator-base/issues/81
