### ISSUE TITLE
Ignore linter for vendor classes

### ISSUE THREAD

**Issue by marcoT89** [Gert-dev/php-integrator-linter#26]
I installed the package symfony/var-dumper and the linter is showing an error in the GeneratorDemo.php class of this package... Well, I think this is not desirable.

What do you think? 

And congratulations for your excellent job dude. I'm migrating from Sublime Text 3 with SublimeCodeIntel to Atom because of your php-integrator-* packages! Really nice work man!

Thnks!

**Comment by Gert-dev** [comment]
Thanks for your kind words. Am I correct in assuming that you mentioned this because GeneratorDemo is actually a test file? In that case, I agree that it probably should not be linted.

The linter package itself has no clue of what files are indexed or not (it just tries to lint them). However, the base package does know what files are indexed, but it does not know which PHP files to ignore. This will be added at some point in the future (see also [1]).

In this case these test files will need to be manually excluded from the indexing process because they also use the .php extension and the indexer has no idea whether this is an actual part of your codebase or just a test file. Some code bases solve this by calling PHP test files something like `MyTest.phpt` or `MyTest.php-test` so tools don't pick up these files as actual code.

[1] https://github.com/Gert-dev/php-integrator-base/issues/113

**Comment by Gert-dev** [comment]
I'll close this since the ignoring of certain files and folders is already taken up in the linked issue (so I can keep the discussion centralized). Thanks for your input and if you have any other questions or problems, feel free to report them!

**Comment by marcoT89** [comment]
Ok! Thanks!
