### ISSUE TITLE
Shows warnings about unresolved use statements.

### ISSUE THREAD

**Issue by aitboudad** [Gert-dev/php-integrator-linter#34]
Currently it show only the class name not found, but not in the use statements.

**Comment by Gert-dev** [comment]
Hi, did I understand correctly that you would like errors to be reported for use statements for class names that do not exist instead of warnings about unused use statements?

```php
use Some\NonExistent\Class;
//     -------------------
//     Error: class does not exist!
```

**Comment by aitboudad** [comment]
yes

**Comment by Gert-dev** [comment]
I've been looking to implement this, but after looking at it in detail, I don't think it's possible. The problem is that use statements don't necessarily represent an element; I can't detect whether an import is actually just a name import or an actual element import, for example:

```php
use Classes\Foo; // Element import, could validate this.
use const Classes\Constant; // Element import, could validate this.
use Classes; // This may or may not actually be a class. It could just be a convenience
             // import to access Classes\Foo in the code below. Showing "Unknown class"
             // here would be wrong.
```

In case I'm missing something, do let me know, but as far as I can currently see, there is no way to correctly distinguish between the types of the import (if it doesn't exist, it could be a missing class or just a namespace import).
