### ISSUE TITLE
Separate config for disabled missing doc warnings

### ISSUE THREAD

**Issue by hultberg** [Gert-dev/php-integrator-linter#43]
Hello! I noticed that there is no separate config to disable the "missing docs" on a method/function/(and so on), but only "Validate docblock correctness".

I would like to separate the issues of not having a doc and actually validating existing docs.

**Comment by hultberg** [comment]
@Gert-dev I have created a branch that fixes this issue, but I'm having trouble testing it because it seems `php-integrator-base` package isn't working with `atom -d` on any branch other than `master`. Do you know whats going on here?

**Comment by hultberg** [comment]
@Gert-dev Done som digging, and it seems `@activeProject` is null in Main.coffee, and this makes base package unable to index. Do you have a set of requires for making base package work in development mode?

**Comment by Gert-dev** [comment]
About your referenced code changes: if you just want to skip missingDocumentation from being parsed by the linter, it is _probably_ easier to just not parse it in the linter package itself [1].

However, iIf you want to add it to the PHP side, I'd much rather see it not detect them at all instead of detect them and then drop them (otherwise you still get the performance hit from scanning for them without actually using them).

About your last post: not sure if you follow the latest developments (no worries if you don't, I don't expect anyone to), but basic project support is already present in the development branch, which means you'll need the [atom-project-manager](https://github.com/danielbrodin/atom-project-manager) plugin. See also [2].

[1] https://github.com/Gert-dev/php-integrator-linter/blob/master/lib/SemanticLintProvider.coffee#L239
[2] https://github.com/Gert-dev/php-integrator-base/blob/development/CHANGELOG.md

**Comment by hultberg** [comment]
@Gert-dev The reason I didn't add an if in the SemanticLintProvider.coffee is because I observed that no other options did it, so I tried to follow the "norm". I'll try to include atom-project-manager to see if that helps.

**Comment by hultberg** [comment]
@Gert-dev Edit: After reading the CHANGELOGs I managed to get it working in development mode. Thanks! A facepalm to myself. 😄

**Comment by Gert-dev** [comment]
Thanks for the PR! I've just released a new version that includes it.
